version: 2.1

machine: true

orbs:
  maven: archmix/maven@2

workflows:
  version: 2
  build-deploy:
    jobs:
      - maven/build:
          name: build
          context: Archmix
      - maven/release:
          context: Archmix
          requires:
            - build
          filters:
            branches:
              only: master